services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: hassan915/financial-adviser-client:latest
    container_name: client
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: hassan915/financial-adviser-server:latest
    container_name: server
    ports:
      - "8000:8000"
    env_file: 
      - server/.env   
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=financial_advisor

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: